### ISSUE TITLE
Yank gem

### ISSUE THREAD

**Issue by krainboltgreene** [krainboltgreene/shogun.gem#17]
- [ ] Contact the rubygems.org body to have it fully yanked
- [ ] Yank each version if that doesn't work
- [ ] Update the metadata if that doesn't work
